package solutions;

/*
 * 
 * PROJECT EULER - SOLUTION 0002
 * -----------------------------
 * 
 * GIVEN: Each new term in the Fibonacci sequence is generated by adding the
 * previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * four million, find the sum of the even-valued terms.
 * 
 * -----------------------------
 * ANSWER: 4613732
 * 
 */
public class Solution0002 {
	
	private static long FIB_0 = 1;
	private static long FIB_1 = 1;
	
	public static void main(String[] args) {
		System.out.println("Sum of even fibonacci numbers that do not exceed 4 million: " + evenFibonacciSum(4_000_000));
	}
	
	private static long evenFibonacciSum(int limit) {
		if(limit > 4_000_000) {
			System.out.println("Maximum limit is 4 million, exiting program.");
			
			return -1;
		}
		
		long prev1 = FIB_0;
		long prev2 = FIB_1;
		long curr  = 0;
		long sum   = 0;
		
		while(curr < limit) {
			curr = prev1 + prev2;
			
			if(curr % 2 == 0) {
				sum += curr;
			}
			
			prev1 = prev2;
			prev2 = curr;
		}
		
		return sum;
	}

}
